spring.application.name=StartSmart AI

spring.profiles.active=local

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# HikariCP
spring.datasource.hikari.max-lifetime=250000
